CTFd-Unique_flags/models.py
# Code from https://github.com/Isotech42/CTFd-RedHerring/blob/main/models.py
from CTFd.models import db, Teams, Challenges, Flags, Users

from CTFd.models import db, Challenges

class CheaterTeams(db.Model):
    """
    Model for the cheater_teams table

    Columns:
        id (int): The ID of the record
        challengeid (int): The ID of the challenge
        cheaterid (int): The ID of the cheater
        cheatteamid (int): The ID of the team that maybe cheated
        sharerteamid (int): The ID of the team that shared the flag
        flagid (int): The ID of the flag
        date (datetime): The date of the record creation
    """

    __tablename__ = 'cheater_teams'

    id = db.Column(db.Integer, primary_key=True)
    challengeid = db.Column(db.Integer, db.ForeignKey('challenges.id', ondelete="CASCADE"))
    cheaterid = db.Column(db.Integer, db.ForeignKey('users.id', ondelete="CASCADE"))
    cheatteamid = db.Column(db.Integer, db.ForeignKey('teams.id', ondelete="CASCADE"))
    sharerteamid = db.Column(db.Integer, db.ForeignKey('teams.id', ondelete="CASCADE"))
    flagid = db.Column(db.Integer, db.ForeignKey('flags.id', ondelete="CASCADE"))
    date = db.Column(db.DateTime, default=db.func.current_timestamp())

    def __init__(self, challengeid, cheaterid, cheatteamid, sharerteamid, flagid):
        """ Initializes the CheaterTeams object
        Args:
            challengeid (int): The ID of the challenge
            cheaterid (int): The ID of the cheater
            cheatteamid (int): The ID of the team that maybe cheated
            sharerteamid (int): The ID of the team that shared the flag
            flagid (int): The ID of the flag
        """
        self.challengeid = challengeid
        self.cheaterid = cheaterid
        self.cheatteamid = cheatteamid
        self.sharerteamid = sharerteamid
        self.flagid = flagid

    def __repr__(self):
        """ 
        Returns the string representation of the CheaterTeams object
        """
        return "<CheaterTeams Team {0} maybe cheated for challenge {1} with the flag {2} belonging to the team {3} at {4} >".format(self.cheatteamid, self.challengeid, self.flagid, self.sharerteamid, self.date)
    
    def cheated_team_name(self):
        """ 
        Get the name of the team that maybe cheated
        """
        return Teams.query.filter_by(id=self.cheatteamid).first().name

    def shared_team_name(self):
        """
        Get the name of the team that shared the flag
        """
        return Teams.query.filter_by(id=self.sharerteamid).first().name

    def challenge_name(self):
        """
        Get the name of the challenge
        """
        return Challenges.query.filter_by(id=self.challengeid).first().name
    
    def cheater_name(self):
        """
        Get the name of the cheater
        """
        return Users.query.filter_by(id=self.cheaterid).first().email

CTFd-Unique_flags/__init__.py
import os
from CTFd.models import db
from CTFd.plugins import register_plugin_assets_directory
from CTFd.plugins.migrations import upgrade
from CTFd.plugins.flags import CTFdStaticFlag, FLAG_CLASSES
from CTFd.utils.user import get_current_team, get_current_user
from .routes import plugin_blueprint
from .models import CheaterTeams

directory_name = os.path.dirname(__file__).split(os.sep)[-1] # Get the directory name of this file

class UniqueFlag(CTFdStaticFlag):

    name = "uniqueflag"
    templates = {  # Nunjucks templates used for key editing & viewing
        "create": f"/plugins/{directory_name}/assets/unique/create.html",
        "update": f"/plugins/{directory_name}/assets/unique/edit.html",
    }

    @staticmethod
    def compare(chal_key_obj, provided_flag):
        """
        Compare the provided flag to the saved flag

        Args:
            chal_key_obj: A CTFd.models.Flags object
            provided_flag: A string provided by the user


        Returns:
            bool: Whether or not the provided flag is correct
        """
        # Get the actual flag to check for the challenge submitted (the function compare() is called for each flag of the challenge)

        saved_flag = chal_key_obj.content
        curr_team_id = get_current_team().id

        if len(saved_flag) != len(provided_flag):
            return False

        result = 0

        for x, y in zip(saved_flag, provided_flag):
            result |= ord(x) ^ ord(y)

        if result != 0:
            return False
        
        # Check if the team id of the player is the same as the team id of the flag data
        # True = the flag is correct and the player is in the right team
        # False = the flag is correct but the player is not in the right team
        team_id = chal_key_obj.data
        if int(team_id) == int(curr_team_id):
            return True
        
        # The player is not in the right team, so we add the record in the cheater_teams table
        curr_user_id = get_current_user().id
        cheater = CheaterTeams(challengeid=chal_key_obj.challenge_id, cheaterid=curr_user_id, cheatteamid=curr_team_id, sharerteamid=team_id, flagid=chal_key_obj.id)
        db.session.add(cheater)
        return False



def load(app):
    """ 
    Load the plugin into CTFd
    Creates the database table and registers the blueprint
    """
    app.db.create_all()
    app.register_blueprint(plugin_blueprint)


    upgrade(plugin_name="unique_flags")
    FLAG_CLASSES['uniqueflag'] = UniqueFlag
    register_plugin_assets_directory(
        app, base_path=f"/plugins/{directory_name}/assets/"
    )

CTFd-Unique_flags/routes.py
import os
from flask import redirect, render_template, request, url_for, Blueprint
from flask import Blueprint
from CTFd.utils.decorators import admins_only
from .models import CheaterTeams
from CTFd.models import Challenges, Flags, db
from CTFd.utils.helpers import info_for, error_for
from .utils import importFlag
from CTFd.utils.helpers import get_errors, get_infos

plugin_blueprint = Blueprint("unique_flags", __name__, template_folder="templates")


@plugin_blueprint.route("/admin/unique-flag", methods=["GET", "POST"])
@admins_only
def home():
    """ Import unique flags or show the unique flags administration page

    Returns:
        render_template: Render the admin-import.html template or redirects to the unique_flags.home page
    """
    infos = get_infos()
    errors = get_errors()

    if request.method == "GET":
        challenges = Challenges.query.all()
        return render_template('admin-import.html', infos=infos, errors=errors, challenges=challenges)


    if request.method == "POST":

        infos, errors = importFlag(request.form["content"])

        for info in infos:
            info_for("unique_flags.home", info)
        for error in errors:
            error_for("unique_flags.home", error)

        return redirect(url_for("unique_flags.home"))
 
 
@plugin_blueprint.route("/admin/unique-flag/delete-flags", methods=["POST"])
@admins_only
def delete_flags():
    """ Deletes all unique flags or flags of a specific challenge

    Returns:
        redirection: Redirects to the unique_flags.home page
    """
    if request.form.get('challenge_id') is None:
        count = Flags.query.filter_by(type="uniqueflag").delete()
    else: 
        count = Flags.query.filter_by(type="uniqueflag", challenge_id=request.form.get('challenge_id')).delete()
    
    db.session.commit()

    info_for("unique_flags.home", f"{count} occurrence(s) deleted")

    return redirect(url_for("unique_flags.home"))
 

@plugin_blueprint.route("/admin/unique-flag/cheating-monitor", methods=["GET"])
@admins_only
def view_cheater():
    """ View the cheater teams

    Returns:
        render_template: Render the cheat-monitor.html template
    """
    return render_template('cheat-monitor.html', cheaters=CheaterTeams.query.all())

CTFd-Unique_flags/templates/admin-import.html
{% extends "admin/base.html" %} 

{% block stylesheets %}
{#

Réutilisation du components/errors.html sauf qu'il manque bootstrap sur le page admin pour 
que le components soit interactif, donc la possibilité de supprimer l'alerte est retirée  

#}
<style>
  .btn-close{
    display: none;
  }
</style>
{% endblock %} 



{% block
content %}
<style>
  .body {
    margin-top: 3vh;
  }
</style>
<div class="container body">
  {% include "components/errors.html" %}

  <h2>Unique Flags Import</h2>
  <p>

    {{enabled}}
    Please encode your flags in CSV format as in the example file
    <a href="/plugins/CTFd-Unique_flags/assets/example.csv">flags.csv</a>
  </p>
  <form method="POST">
    <div id="writeup-editor">
      <textarea id="new-desc-editor" class="form-control" rows="10" name="content"></textarea>
    </div>

    <div class="mt-1">
      <input type="file" id="csv" name="csv" accept=".csv">
      <button class="btn btn-success btn-outlined float-right " type="submit">
        Insert flags
      </button>
    </div>
    <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
  </form>
<br>
  <div>
    <hr>
    <h2>Plugin configuration</h2>
    <br>
    <h4>Resetting flags</h4>
    <p>This function will delete all flags, but will not reset any resolutions already made. </p>
    <form method="POST" action="{{ url_for('unique_flags.delete_flags')}}">
        <button class="btn btn-danger btn-outlined float-left" type="submit">
          Delete all unique flags
        </button>
      <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
    </form>

    <br>
    </div>
    <div class="mt-5">
    <h4>Delete a series of flags</h4>
    <p>This function will remove all flags linked to a challenge.</p>
    
    <form method="POST" action="{{ url_for('unique_flags.delete_flags')}}">
      <label for="challenge_id">Challenge</label>
      <select class="form-control w-50" name="challenge_id">
        {% for challenge in challenges %}
          <option value="{{ challenge.id }}">{{ challenge.name }} ({{ challenge.category }})</option>
        {% endfor %}
      </select>
        <button class="btn btn-danger btn-outlined mt-3 mb-3" type="submit">
          Delete all unique flags for a challenge
        </button>
      <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
    </form>
  </div>
</div>


{% endblock %}


{% block scripts %}
<script>
  function handleFileSelect(evt) {
    var file = evt.target.files[0];
    var reader = new FileReader();
    reader.onload = function(e) {
      document.getElementById('new-desc-editor').value = e.target.result;
    };
    reader.readAsText(file);
  }

  document.getElementById('csv').addEventListener('change', handleFileSelect, false);
</script>
{% endblock %} 

CTFd-Unique_flags/templates/cheat-monitor.html
{# Based on https://github.com/Isotech42/CTFd-RedHerring/blob/main/templates/red_herring.html #}

{% extends "admin/base.html" %} {% block stylesheets %} {% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Cheat monitor</h1>
		</div>
	</div>
    <div class="container">
        <div id="cheat" class="row">
            <div class="col-md-12">
                <p>Make sure that the flags have enough entropy to know whether there has just been a typo or a real case of cheating.</p>
                <table class="table table-striped">
                    <thead class="text-center">
                        <tr>
                            <td scope="col" width="10px"><b>ID</b></td>
                            <td scope="col"><b>Challenge</b></td>
                            <td scope="col"><b>Cheater</b></td>
                            <td scope="col"><b>Cheating team</b></td>
                            <td scope="col"><b>Sharing team</b></td>
                            <td scope="col"><b>Date</b></td>
                        </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for cheater in cheaters %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td><a href="{{ url_for('admin.challenges_detail', challenge_id = cheater.challengeid )}}">{{ cheater.challenge_name() }}</a></td>
                            <td><a href="{{ url_for('admin.users_detail', user_id = cheater.cheaterid )}}">{{cheater.cheater_name()}}</a></td>
                            <td><a href="{{ url_for('admin.teams_detail', team_id = cheater.cheatteamid )}}">{{ cheater.cheated_team_name() }}</a></td>
                            <td><a href="{{ url_for('admin.teams_detail', team_id = cheater.sharerteamid )}}">{{ cheater.shared_team_name() }}</a></td>
                            <td>{{ cheater.date }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}