CTFd-Writeup/models.py
from CTFd.models import db
from sqlalchemy.orm import relationship
from sqlalchemy import Integer, Text, Boolean, Column, ForeignKey


class WriteupModel(db.Model):
    """
    Model for the writeups table
    """
    __tablename__ = "writeups"
    id = Column(Integer, ForeignKey('challenges.id', ondelete="CASCADE"), primary_key=True)
    content = Column(Text)
    visible = Column(Boolean, default=False)
    challenge = relationship('Challenges', uselist=False, backref='writeups')

    def __init__(self, id, content, visible):
        self.id = id
        self.content = content
        self.visible = visible

CTFd-Writeup/__init__.py
from .routes import plugin_blueprint
from pathlib import Path
from CTFd.utils.plugins import override_template
from CTFd.utils import config, get_config, set_config

def load(app):
    """
    Load the plugin into CTFd, registers the blueprint and creates the database table
    Overrides the challenge.html template if the plugin is enabled
    """

    app.db.create_all() 
    app.register_blueprint(plugin_blueprint)
    dir_path = Path(__file__).parent.resolve()
    template_path = dir_path / 'templates' / 'custom-challenge.html'

    # First run initialize to enabled
    if get_config("plugin_writeup_enabled") is None:
        set_config("plugin_writeup_enabled", True)

    if get_config("plugin_writeup_enabled"):
        # Overwrite the challenge.html template only when the plugin is enabled
        override_template('challenge.html', open(template_path).read())

CTFd-Writeup/routes.py
from flask import render_template, Blueprint, request, redirect, url_for, session
from CTFd.models import Solves, Challenges, db
from CTFd.utils.decorators import admins_only
from .models import WriteupModel
from CTFd.utils.user import  get_current_team, get_current_user_attrs
from CTFd.utils.helpers import get_errors, get_infos
from CTFd.utils.helpers import info_for, error_for
from .decorators import plugin_enabled
from CTFd.utils import config, get_config, set_config
from CTFd.utils.decorators import authed_only

plugin_blueprint = Blueprint('writeup', __name__, template_folder='templates')

@plugin_blueprint.route("/writeup/<int:challenge_id>", methods=["GET"])
@plugin_enabled
@authed_only
def view_writeup(challenge_id):
    """
    View the writeup for a challenge if it is unlocked
    """
    if challenge_is_unlocked(challenge_id):
        return render_template('custom-page.html', content=get_writeup(challenge_id))
    else:
        return render_template('error.html')

@plugin_blueprint.route("/admin/writeup", methods=["GET"])
@admins_only
def view_admin_writeup():
    """
    View the writeup for a challenge
    """
    infos = get_infos()
    errors = get_errors()

    if not get_config("plugin_writeup_enabled"):
        errors.append("Please note that the plugin is currently disabled.")

    return render_template('writeup_config.html', challenges=get_all_challenges(), infos=infos, errors=errors, config=get_config("plugin_writeup_enabled"))

@plugin_blueprint.route("/admin/writeup", methods=["POST"])
@admins_only
def admin_update_config():
    """
    Update the plugin configuration and display the writeup configuration page
    """
    infos = get_infos()
    errors = get_errors()

    if request.form.get("plugin_enabled") == "on":
        set_config("plugin_writeup_enabled", True)
        infos.append("Plugin enabled, server restart required for changes to take effect.")
    else:
        set_config("plugin_writeup_enabled", False)
        infos.append("Plugin disabled, a server restart is required for changes to take effect.")

    return render_template('writeup_config.html', challenges=get_all_challenges(), infos=infos, errors=errors, config=get_config("plugin_writeup_enabled"))


@plugin_blueprint.route("/admin/writeup/edit/<int:challenge_id>", methods=["GET", "POST"])
@admins_only
def edit_writeup(challenge_id):
    """
    Edit the writeup for a challenge

    Args:
        challenge_id (int): The challenge ID

    Returns:
        render_template: Render the writeup_editor.html template or redirects to the writeup.view_admin_writeup page
    """
    if request.method == "GET":
        writeup = WriteupModel.query.filter_by(id=challenge_id).first()
        challenge = get_challenge_by_id(challenge_id)

        return render_template('writeup_editor.html', challenge_info=challenge, writeup=writeup)

    if request.method == "POST":

        try: 
            writeup = WriteupModel.query.filter_by(id=challenge_id).first()

            # Create new writeup model instance if it doesn't exist
            if not writeup:
                writeup = WriteupModel(challenge_id, request.form["description"], True)
            else:
                writeup.content = request.form["description"]

            db.session.add(writeup)
            db.session.commit()

            info_for(
                "writeup.view_admin_writeup",
                f"Successfully updated writeup for challenge {challenge_id}.",
            )
            return redirect(url_for('writeup.view_admin_writeup'))

        except Exception as e:
            print(e)

            error_for(
                "writeup.view_admin_writeup",
                f"Failed to update writeup for challenge {challenge_id}.",
            )

            return redirect(url_for('writeup.view_admin_writeup'))

@plugin_blueprint.route("/admin/writeup/delete/<int:challenge_id>", methods=["POST"])
@admins_only
def delete_writeup(challenge_id):
    """
    Delete the writeup for a challenge

    Args:
        challenge_id (int): The challenge ID

    Returns:
        dict: A JSON object containing the status of the deletion
    """
    writeup = WriteupModel.query.filter_by(id=challenge_id).first_or_404()
    db.session.delete(writeup)
    db.session.commit()

    info_for(
        "writeup.view_admin_writeup",
        f"Successfully deleted writeup for challenge {challenge_id}.",
    )

    return {"success": True}


@plugin_blueprint.route("/admin/writeup/visibility/<int:challenge_id>", methods=["PUT"])
@admins_only
def toogle_writeup_visibility(challenge_id):
    """
    Toggle the visibility of a writeup

    Args:
        challenge_id (int): The challenge ID

    Returns:
        dict: A JSON object containing the status of the visibility change
    """
    writeup = WriteupModel.query.filter_by(id=challenge_id).first_or_404()
    writeup.visible = not writeup.visible

    db.session.commit()

    info_for(
        "writeup.view_admin_writeup",
        f"Challenge {writeup.challenge.name} ({writeup.id}) is now {'visible' if writeup.visible else 'hidden'}",
    )

    return {"success": True}



def challenge_is_unlocked(challenge_id):
    """
    Check if a challenge is unlocked for the current user

    Args:
        challenge_id (int): The challenge ID

    Returns:
        bool: Whether the challenge is unlocked or not
    """

    user = get_current_user_attrs()
    team = get_current_team()

    if config.is_teams_mode() and team is not None:
        return db.session.query(Solves).filter(Solves.team_id == user.team_id, Solves.challenge_id == challenge_id).count()
    else:
        return db.session.query(Solves).filter(Solves.user_id == user.id, Solves.challenge_id == challenge_id).count()

def get_writeup(challenge_id):
    """
    Get the writeup for a challenge

    Args:
        challenge_id (int): The challenge ID

    Returns:
        query result: The writeup for the challenge
    """
    return db.session.query(Challenges, WriteupModel).outerjoin(WriteupModel, Challenges.id == WriteupModel.id).filter(Challenges.id == challenge_id, Challenges.state == "visible").first()

def get_all_challenges():
    """
    Get all challenges

    Returns:
        query result: All challenges
    """
    return Challenges.query.all()

def get_challenge_by_id(challenge_id):
    """
    Get a challenge by its ID 

    Args:
        challenge_id (int): The challenge ID

    Returns:
        query result: The challenge
    """
    return Challenges.query.filter_by(id=challenge_id).first_or_404()

CTFd-Writeup/templates/custom-challenge.html
<div
  :class="getStyles()"
  role="document"
  x-data="Challenge"
  x-init="id = {{ challenge.id }}"
>
  <div class="modal-content">
    <div class="modal-body py-4 px-4 px-sm-5">
      <div>
        <button
          type="button"
          class="btn-close float-end"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>

        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a
              class="nav-link active"
              data-bs-target="#challenge"
              @click="showChallenge()"
            >
              {% trans %}Challenge{% endtrans %}
            </a>
          </li>

          {% block solves %}
          <li class="nav-item">
            <a
              class="nav-link challenge-solves"
              data-bs-target="#solves"
              @click="showSolves()"
            >
              {% if solves != None %} {{ ngettext("%(num)d Solve", "%(num)d
              Solves", solves) }} {% endif %}
            </a>
          </li>
          {% endblock %}

          <li class="nav-item">
            <a
              class="nav-link challenge-solves"
              data-bs-target="#solutions"
              href="{{ url_for('writeup.view_writeup', challenge_id = challenge.id) }}"
            >
              Solution
            </a>
          </li>
        </ul>
      </div>

      <div>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane fade show active" id="challenge">
            <h2 class="challenge-name text-center pt-3">
              {{ challenge.name }}
            </h2>
            <h3 class="challenge-value text-center">{{ challenge.value }}</h3>

            {% if tags %}
            <div class="challenge-tags text-center pt-2 pb-3">
              {% block tags %} {% for tag in tags %}
              <span class="challenge-tag badge bg-info">{{ tag }}</span>
              {% endfor %} {% endblock %}
            </div>
            {% endif %}

            <span class="challenge-desc"
              >{% block description %}{{ challenge.html }}{% endblock %}</span
            >

            {% if challenge.connection_info %}
            <div class="mb-2">
              <span class="challenge-connection-info">
                {% block connection_info %} {% set conn =
                challenge.connection_info %} {% if not conn %} {% elif
                conn.startswith("http") %} {{ conn | urlize(target="_blank") }}
                {% else %}
                <code>{{ conn }}</code>
                {% endif %} {% endblock %}
              </span>
            </div>
            {% endif %} {% if hints %}
            <div class="challenge-hints hint-row row">
              <div class="col-12 mb-3">
                {% for hint in hints | sort(attribute="cost") %}
                <div x-data="Hint" x-init="id = {{ hint.id }}">
                  {% if hint.content %}
                  <details>
                    <summary>{% trans %}View Hint{% endtrans %}</summary>
                    <div>{{ hint.html | safe }}</div>
                  </details>
                  {% else %}
                  <details @toggle="showHint(event)">
                    <summary>
                      Unlock Hint for {{ hint.cost }} point{{
                      hint.cost|pluralize }}
                    </summary>
                    <div x-html="html"></div>
                  </details>
                  {% endif %}
                </div>
                {% endfor %}
              </div>
            </div>
            {% endif %} {% if files %}
            <div class="row challenge-files text-center pb-3">
              {% for file in files %}
              <div
                class="col-md-4 col-sm-4 col-xs-12 file-button-wrapper d-block"
              >
                {% set segments = file.split('/') %} {% set token =
                file.split('?') | last %} {% if token %} {% set filename =
                segments | last | replace("?" + token, "") %} {% else %} {% set
                filename = segments | last %} {% endif %}
                <a
                  class="btn btn-info btn-file mb-1 d-inline-block px-2 w-100 text-truncate"
                  href="{{ file }}"
                  title="{{ filename }}"
                >
                  <i class="fas fa-download"></i>
                  <small> {{ filename }} </small>
                </a>
              </div>
              {% endfor %}
            </div>
            {% endif %} {% if max_attempts > 0 %}
            <div class="row text-center">
              <div class="col-12">
                <p>
                  {{ attempts }}/{{ max_attempts }} attempt{{
                  max_attempts|pluralize }}
                </p>
              </div>
            </div>
            {% endif %}

            <div class="row submit-row">
              <div class="col-12 col-sm-8">
                {% block input %}
                <input
                  id="challenge-id"
                  class="challenge-id"
                  type="hidden"
                  value="{{ challenge.id }}"
                />
                <input
                  id="challenge-input"
                  class="challenge-input form-control"
                  type="text"
                  name="submission"
                  @keyup.enter="submitChallenge()"
                  placeholder="{% trans %}Flag{% endtrans %}"
                  x-model="submission"
                />
                {% endblock %}
              </div>

              <div class="col-12 col-sm-4 mt-3 mt-sm-0 key-submit">
                {% block submit %}
                <button
                  id="challenge-submit"
                  class="challenge-submit btn btn-outline-secondary w-100 h-100"
                  type="submit"
                  @click.debounce.500ms="submitChallenge()"
                >
                  {% trans %}Submit{% endtrans %}
                </button>
                {% endblock %}
              </div>
            </div>

            <div class="row notification-row">
              <div class="col-12">
                <template x-if="response">
                  {# This alert is re-used for all alerts, so it's important not
                  to make it dismissble #}
                  <div
                    :class="{
                          'alert text-center w-100 mt-3 alert-success': response.data.status == 'correct',
                          'alert text-center w-100 mt-3 alert-info': response.data.status == 'already_solved',
                          'alert text-center w-100 mt-3 alert-danger': response.data.status == 'incorrect',
                        }"
                    role="alert"
                  >
                    <strong x-text="response.data.message"></strong>
                    <div
                      x-show="(response.data.status == 'correct' || response.data.status == 'already_solved')"
                    >
                      <div x-show="getNextId()">
                        <button
                          @click="nextChallenge()"
                          class="btn btn-info mt-3"
                        >
                          {% trans %}Next Challenge{% endtrans %}
                        </button>
                      </div>
                      {% if Configs.social_shares %}
                      <div>
                        <button
                          x-show="!share_url"
                          @click="getShareUrl()"
                          class="btn btn-sm btn-outline-info mt-3"
                        >
                          {% trans %}Share{% endtrans %}
                        </button>
                        <div
                          class="btn-group mt-3"
                          role="group"
                          x-show="share_url"
                        >
                          <button
                            type="button"
                            class="btn btn-sm btn-outline-secondary"
                            @click="copyShareUrl()"
                            data-bs-toggle="tooltip"
                            data-bs-title="Copied!"
                          >
                            <i class="fa-solid fa-copy"></i>
                          </button>
                          <a
                            :href="'https://twitter.com/intent/tweet?url=' + encodeURIComponent(share_url)"
                            role="button"
                            class="btn btn-sm btn-outline-secondary"
                            target="_blank"
                          >
                            <i class="fa-brands fa-twitter"></i>
                          </a>
                          <a
                            :href="'https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(share_url)"
                            role="button"
                            class="btn btn-sm btn-outline-secondary"
                            target="_blank"
                          >
                            <i class="fa-brands fa-facebook-f"></i>
                          </a>
                          <a
                            :href="'http://www.linkedin.com/shareArticle?url=' + encodeURIComponent(share_url)"
                            role="button"
                            class="btn btn-sm btn-outline-secondary"
                            target="_blank"
                          >
                            <i class="fa-brands fa-linkedin-in"></i>
                          </a>
                        </div>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </template>
              </div>
            </div>
          </div>

          <div role="tabpanel" class="tab-pane fade" id="solves">
            <div class="row">
              <div class="col-md-12">
                <table class="table table-striped text-center">
                  <thead>
                    <tr>
                      <td>
                        <b>{% trans %}Name{% endtrans %}</b>
                      </td>
                      <td>
                        <b>{% trans %}Date{% endtrans %}</b>
                      </td>
                    </tr>
                  </thead>
                  <tbody id="challenge-solves-names">
                    <template x-for="solve in solves">
                      <tr>
                        <td>
                          <a :href="solve.account_url" x-text="solve.name"></a>
                        </td>
                        <td x-text="solve.date"></td>
                      </tr>
                    </template>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

CTFd-Writeup/templates/custom-page.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Writeup : {{ content[0].name }}</h1>
    <h2>{{ content[0].category }}</h2>
  </div>
</div>

<div class="container">
  {% if content[0].description %}
  <h2>Description:</h2>
  <p>{{ content[0].description | markdown | safe }}</p>
  {% endif %} 
  
  <hr />
  
  {% if content[1].content and content[1].visible %}
  
  <h2>Solution :</h2>
  <p>{{ content[1].content | markdown | safe }}</p>
  {% else %}
  <h2>Solution :</h2>
  <p>No solution currently available</p>
  {% endif %}
</div>

{% endblock%}

CTFd-Writeup/templates/error.html
{% extends "base.html" %} {% block content %}

<div class="jumbotron">
  <div class="container">
    <h1>Error</h1>
  </div>
</div>

<div class="container text-center">
  <h2>You haven't solved the challenge yet</h2>
  <a type="button" class="btn btn-primary" href="{{ url_for('challenges.listing')}}"
    >Back to challenges </a
  >
</div>
{% endblock%}

CTFd-Writeup/templates/writeup_config.html
{% extends "admin/base.html" %}  

{% block stylesheets %} 

<style>
  .body {
    margin-top: 3vh;
  }

  .btn-close{
    display: none;
  }
</style>
{#

Réutilisation du components/errors.html sauf qu'il manque bootstrap sur le page admin pour 
que le components soit interactif, donc la possibilité de supprimer l'alerte est retirée  

#}

{% endblock %}


{% block content %}


<div class="container body">
  {% include "components/errors.html" %}

  <h2>Writeup Edition</h2>

  <!-- Confirmation Modal -->
  <div class="modal fade" id="confirmationModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalLabel">Confirm Deletion</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to delete this data?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>
        </div>
      </div>
    </div>
  </div>
  
  
  
  <div id="scoreboard" class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
          <tr>
            <td scope="col" width="10px"><b>ID</b></td>
            <td scope="col"><b>Name</b></td>
            <td scope="col"><b>Category</b></td>
            <td scope="col"><b>Type</b></td>
            <td scope="col"><b>Visible</b></td>
            <td scope="col"><b>Action</b></td>
          </tr>
        </thead>
        <tbody>
          {% for challenge in challenges %}
          <tr>
            <th scope="row" class="text-center">{{ challenge.id }}</th>
            <td>{{ challenge.name }}</td>
            <td>{{ challenge.category }}</td>
            <td>{{ challenge.type }}</td>
            {% if challenge.writeups[0] %}
              <td>{% if challenge.writeups[0].visible %}Yes{% else %}No{% endif %}</td>
            {% else %}
              <td>Non-existent</td>
            {% endif %}
            <td>
              <a 
                href="{{url_for('writeup.edit_writeup', challenge_id=challenge.id)}}"
                class="btn btn-outline-secondary"
                data-toggle="tooltip"
                title=""
                id="writeup-edit-button"
                data-original-title="Edit writeup"
              >
                <i class="btn-fa fas fa-pencil-alt"></i>
              </a>
  
              {% if challenge.writeups[0] %}
              <button type="button" class="btn btn-outline-warning toggle-visibility" data-challenge-id="{{ challenge.id }}" title="Toggle visibility">
                <i class="fas fa-eye{{ '' if challenge.writeups[0].visible else '-slash' }}"></i>
              </button>
              <button type="button" class="btn btn-outline-danger action-btn" data-action="delete" data-challenge-id="{{ challenge.id }}" data-toggle="modal" data-target="#confirmationModal" title="Delete writeup">
                  <i class="fas fa-trash-alt"></i>
              </button>
              {% endif %}
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
  

  <hr>
  <h2>Plugin configuration</h2>
  <form method="POST">
      <div class="form-check">
          <input class="form-check-input" name="plugin_enabled" type="checkbox" {% if config %}checked{% endif %} id="defaultCheck1">
          <label class="form-check-label" for="defaultCheck1">
            Activate plugin
          </label>
      </div>
      <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
      <button type="submit" class="btn btn-primary mt-3">Save</button>
  </form>

  
</div>

{% endblock %}


{% block scripts %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const actionButtons = document.querySelectorAll('.action-btn');
    const toggleButtons = document.querySelectorAll('.toggle-visibility');
  
    // Handle delete actions with modal confirmation
    actionButtons.forEach(button => {
      button.addEventListener('click', function() {
        const challengeId = this.getAttribute('data-challenge-id');
        const confirmBtn = document.getElementById('confirmDelete');
        
        confirmBtn.onclick = () => {
          fetch(`writeup/delete/${challengeId}`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'CSRF-Token': '{{ Session.nonce }}'
            }
          })
          .then(response => {
            if(response.ok) {
              $('#confirmationModal').modal('hide');
              location.reload();
            } else {
              alert("Failed to delete the challenge.");
            }
          })
          .catch(error => console.error('Error:', error));
        };
  
        $('#confirmationModal').modal('show');
      });
    });
  
    // Handle visibility toggles directly without modal
    toggleButtons.forEach(button => {
      button.addEventListener('click', function() {
        const challengeId = this.getAttribute('data-challenge-id');
        fetch(`writeup/visibility/${challengeId}`, {
          method: 'PUT',
          headers: {
            'Content-Type': 'application/json',
            'CSRF-Token': '{{ Session.nonce }}'
          }
        })
        .then(response => response.json())
        .then(data => {
          if(data.success) {
            location.reload();  // Or dynamically update the icon and status on the page without reloading
          } else {
            alert("Failed to toggle visibility.");
          }
        })
        .catch(error => console.error('Error:', error));
      });
    });
  });
  </script>
{% endblock %}

CTFd-Writeup/templates/writeup_editor.html
{% extends "admin/base.html" %} {% block stylesheets %} {% endblock %} {% block
content %}
<style>
  .body {
    margin-top: 3vh;
  }
</style>
<div class="container body">
  <form method="POST">
    <h2>
      Writeup Edition : {{ challenge_info.name}} {% if challenge_info.category
      != "" %} ({{ challenge_info.category }}) {% endif %}
    </h2>
    <div id="writeup-editor">
      <textarea
        id="new-desc-editor"
        class="form-control markdown"
        name="description"
        rows="10"
      >
{{ writeup.content }}</textarea
      >
    </div>

    <div>
      <button class="btn btn-success btn-outlined float-right" type="submit">
        Update
      </button>
    </div>
    <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
  </form>
</div>

{% endblock %}