CTFd-Universal_flag_submitter/__init__.py
import os
from CTFd.plugins.migrations import upgrade
from CTFd.utils.plugins import override_template
from pathlib import Path
from flask import Blueprint
from .routes import plugin_blueprint

directory_name = os.path.dirname(__file__).split(os.sep)[-1] # Get the directory name of this file



def load(app):
    """
    Load the plugin into CTFd and registers the blueprint
    """

    app.register_blueprint(plugin_blueprint)

    upgrade(plugin_name="universal_flag_submitter")

    dir_path = Path(__file__).parent.resolve()
    template_path = dir_path / 'templates' / 'challenges.html'
    override_template('challenges.html', open(template_path).read())

CTFd-Universal_flag_submitter/routes.py
import sqlalchemy

from CTFd.cache import clear_challenges
from CTFd.models import (
    Challenges,
    Solves,
    db,
)
import copy
from flask import Blueprint, redirect, render_template, request, url_for
from CTFd.plugins.challenges import get_chal_class
from CTFd.utils.decorators import admins_only, authed_only, during_ctf_time_only, require_complete_profile, require_verified_emails
from CTFd.utils.helpers import error_for, get_errors, get_infos, info_for
from CTFd.utils.user import get_current_user
from .decorators import is_allowed_to_attempt
from .utils import add_fail, add_solves


plugin_blueprint = Blueprint("universal_flag_submitter", __name__, template_folder="templates")


@plugin_blueprint.route("/attempt-hidden-challenge", methods=["POST"])
@is_allowed_to_attempt
@authed_only
@require_complete_profile
@during_ctf_time_only
@require_verified_emails
#@require_team
def attempt_hidden_challenge():
    """ 
    Attempt to solve a hidden challenge

    Returns:
        dict: A dictionary containing the success status, message, and design
    """
    chall = db.session.query(Challenges).filter(Challenges.state == "visible").all()

    if len(chall) == 0:
        return {"success": False, "message": "No challenges found. Ask administrator to check configuration.", "design": "neutral"}
    
    for challenge in chall:
        chal_class = get_chal_class(challenge.type)
        status, message = chal_class.attempt(challenge, request)

        user = get_current_user()
        
        if status:
            # check if the Solves is already in the database
            alreadySolve = db.session.query(Solves).filter_by(challenge_id=challenge.id, user_id=user.id).first()
            if alreadySolve:
                return {"success": False, "message": "You already solved this challenge.", "design": "neutral"}

            add_solves(challenge.id, request)

            return {"success": status, "message": message, "challenge" : {"id": challenge.id,
                                            "name": challenge.name, 
                                            "category": challenge.category}, "design": "success"}


    add_fail(chall[0].id, request)

    return {"success": status, "message": message, "design": "danger"}


@plugin_blueprint.route("/admin/hide-challenge", methods=["GET", "POST"])
@admins_only
def home():
    """
    Hide challenges from the challenge list and show hidden challenges administration page
    """
    
    if request.method == "GET":
        infos = get_infos()
        errors = get_errors()
        challenges_view = []
        for challenge in Challenges.query.filter_by(state="visible").all():

            checked = (
                challenge.requirements is not None
                and "prerequisites" in challenge.requirements
                and challenge.id in challenge.requirements["prerequisites"]
            )

            challenges_view.append({
                "id": challenge.id,
                "name": challenge.name,
                "category": challenge.category,
                "state": challenge.state,
                "checked": checked
            })

        return render_template('admin-challenge-hide.html', infos=infos, errors=errors, challenges=challenges_view)

    if request.method == "POST":

        challenges = Challenges.query.filter_by(state="visible").all()
        for challenge in challenges:

            challenge.requirements = sqlalchemy.sql.null()

            db.session.commit()
            print(f"Removed prerequisites from challenge ID {challenge.id}")


        for challenge in request.form.getlist("challenges"):
            challenge = Challenges.query.filter_by(id=challenge).first()
            requirements = {"prerequisites" : [int(challenge.id)]}

            challenge.requirements = copy.deepcopy(requirements)
            db.session.commit()

        clear_challenges()
        info_for("universal_flag_submitter.home", "Saved changes")


        return redirect(url_for("universal_flag_submitter.home"))

CTFd-Universal_flag_submitter/templates/admin-challenge-hide.html
{% extends "admin/base.html" %}

{% block stylesheets %} 

<style>
  .body {
    margin-top: 3vh;
  }

  .btn-close{
    display: none;
  }
</style>
{#

Réutilisation du components/errors.html sauf qu'il manque bootstrap sur le page admin pour 
que le components soit interactif, donc la possibilité de supprimer l'alerte est retirée  

#}

{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>Blackbox Challenges</h1>
		</div>
	</div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% include "components/errors.html" %}

                <p>Only <span class="badge badge-success">visible</span> challenges will be displayed</p>
                <form method="POST">

                    <ul class="list-group">
                    {% for challenge in challenges %}
                        <li class="list-group-item">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" name="challenges" value="{{ challenge.id }}" id="checkbox" {% if challenge.checked %}checked{% endif %} >
                                <label class="form-check-label" for="checkbox1">
                                    {{ challenge.name }} ({{ challenge.category }}) {% if challenge.checked %}<span class="badge badge-warning">visible when unlocked</span>{% else %}<span class="badge badge-primary">always visible</span>{% endif %}
                                </label>
                            </div>
                        </li>
                    {% endfor %}

                    </ul>
                    <input type="hidden" value="{{ Session.nonce }}" name="nonce" id="nonce" />
                    <button class="btn btn-primary btn-outlined float-right mt-3" type="submit">
                        Hide/Show challenges
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

CTFd-Universal_flag_submitter/templates/challenges.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <div class="container">
      <h1>
        {% trans %}Challenges{% endtrans %}
      </h1>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {% include "components/errors.html" %}
      </div>
    </div>
    <p>
      Enter the flag here to validate the challenge. If the flag is correct, you'll see some information appear.
      </p>
      
      <form  method="post">
        <div class="input-group mb-3">
            <input type="text" name="submission" class="form-control no-border" placeholder="Flag" />
            <button class="btn btn-outline-secondary" type="submit">
              Soumettre
            </button>
          </div>
      </form>

      <div id="messageArea"></div>
    
    <div 
      x-data="ChallengeBoard" 
      @load-challenges.window="loadChallenges()" 
      @load-challenge.window="loadChallenge($event.detail)"
    >
      <div
          x-ref="challengeWindow" id="challenge-window" class="modal fade" tabindex="-1" role="dialog" x-data=""
          x-html="$store.challenge.data.view"
      ></div>

      <div x-show="!loaded">
        <div class="min-vh-50 d-flex align-items-center">
          <div class="text-center w-100">
            <i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
          </div>
        </div>
      </div>

      <div x-show="loaded">
        <template x-for="(category, idx) in getCategories()" :key="idx">
          <div class="pt-5">
            <div class="category-header mb-3">
              <h3 x-text="category"></h3>
            </div>

            <div class="category-challenges d-flex flex-column">
              <div class="challenges-row row">
                <template x-for="(c, idx) in getChallenges(category)" :key="c.id">
                  <div class="col-sm-6 col-md-4 col-lg-3">
                    <button
                        class="challenge-button btn btn-dark w-100 text-truncate my-3"
                        :class="c.solved_by_me ? 'challenge-solved' : ''"
                        :value="c.id" @click="loadChallenge(c.id)">
                      <div class="challenge-inner my-3">
                        <p x-text="c.name"></p>
                        <span x-text="c.value"></span>
                      </div>
                    </button>
                  </div>
                </template>
              </div>
            </div>
          </div>
        </template>
      </div>
    </div>
  </div>
{% endblock %}

{% block scripts %}
  {{ Assets.js("assets/js/challenges.js") }}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
        const form = document.querySelector("form");
        const messageArea = document.getElementById('messageArea'); // Obtenez la référence à l'élément où vous voulez ajouter le message
  
        form.addEventListener("submit", function(event) {
            event.preventDefault();
  
            messageArea.innerHTML=`<div class="alert alert-info"><h2>Chargement</h2><p>Please wait</p></div>`;
  
            const submission = document.querySelector("input[name='submission']").value;
            let jsonData = JSON.stringify({ submission: submission });
  
            fetch("{{ url_for('universal_flag_submitter.attempt_hidden_challenge') }}", {
                method: "POST",
                headers: {
                    'Content-Type': 'application/json',
                    'CSRF-Token': window.init.csrfNonce
                },
                body: jsonData
            })
            .then(response => response.json())
            .then(data => {

                let alertClass = getAlertClass(data.design);
  
                if (data.challenge) {
                    let challengeInfo = `Challenge: ${data.challenge.name} (Category: ${data.challenge.category})`;
                    messageArea.innerHTML = `<div class="${alertClass}"><h2>${data.message}</h2><p>${challengeInfo}</p></div>`;
                    reloadChallenges();
                } else {
                    messageArea.innerHTML = `<div class="${alertClass}"><h2>${data.message}</h2></div>`;
                }
  

            })
            .catch(error => {
                console.error('Error sending request:', error);
            });
        });
  
  
        function getAlertClass(design) {
            switch(design) {
                case 'success':
                    return 'alert alert-success';
                case 'danger':
                    return 'alert alert-danger';
                case 'neutral':
                    return 'alert alert-secondary';
                default:
                    return 'alert alert-info';
            }
        }
    });
  
    function reloadChallenges() {
        window.dispatchEvent(new CustomEvent('load-challenges'));
    }
  </script>
  
{% endblock %}